targets:
  - image: jd/shop.png
    desc: 购物车
    checkCar: true
    needWait: true
  - image: jd/game.png
    desc: 游戏
    needWait: true
  - image: jd/grass.png
    desc: 草
    visit: true
  - image: jd/tv.png
    desc: 电视机
  - image: jd/crown.png
    desc: 皇冠(不想入会就移掉这个配置)
    join: true
  - image: jd/vip.png
    desc: vip(不想入会就移掉这个配置)
    join: true
  - image: jd/pack.png
    desc: 包包
    needWait: true
  - image: jd/go_complete.png
    desc: 去完成
    needWait: true